---
title: 'Descriptive Statistics'
author: "Chunyi Wu and Andrzej Galecki"
date: "`r as.character(Sys.Date(), format = '%A %B %d, %Y')`"
output:
  rmdformats::readthedown:
     lightbox: true
     use_bookdown: true
---


```{r knitr-setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment="#>")
```



```{r pacman, echo=FALSE, message=FALSE, warning=FALSE}
if (!require('pacman')) install.packages('pacman', repos = "http://cran.us.r-project.org")
library(pacman)

pacman::p_load(
  readxl,       # load excel file
  glmnet,       # Lasso and Elastic-Net Regularized Generalized Linear Models
  rmdformats,   # rmd formats
  rmarkdown,    # rmarkdown
  here,         # File locator
  skimr,        # get overview of data
  tidyverse,    # data management + ggplot2 graphics 
  janitor,      # adding totals and percents to tables
  flextable,    # format the output table
  gtsummary,    # calculate summary statistics and format the results
  sjPlot,       # correlation matrix
  purrr,        # enhances R functional programming (FP) toolkit 
  tidyr,        #Tools to help to create tidy data
  ggplot2,      #Plot the results
  corrplot
  )
```

# R setup

```{r  rsetup}
sessionInfo()
```

# Univariate statistics


```{r, data-read, echo=FALSE, message=FALSE, warning=FALSE}
xlsx_path = "./Data/jnpx_scrambled_053122.xlsx"

scrambled_orig=readxl::read_excel(xlsx_path, na = "", guess_max = 1000)
scrambled <- scrambled_orig  %>% mutate(log10_B_HBA1C_PRC=log10(B_HBA1C_PRC),log10_DU_ACR=log10(DU_ACR))
```
Raw data are stored in `xlsx_path` file contain `r nrow(scrambled_orig)` rows.  
Variable names are listed below.

```{r var-names}
names(scrambled_orig)
```

```{r, table1, echo=FALSE, message=FALSE, warning=FALSE}
scrambled2 <- scrambled  %>% 
          mutate(Gender=case_when(SEX==1 ~"Male",SEX==2 ~"Female"),
          Status=case_when(CASE_CONTROL==1 ~"Case",CASE_CONTROL==0 ~"Non-case"))%>%                                select(-INDEX,-SEX,-CASE_CONTROL) %>%
          select("Gender","Status","Death" , "FU_TIME" ,"FU_TIME_Death","SBP_TL","DBP_TL" , "AGEONSET_TL" , "BMI_TL","AGE_TL" , "B_HBA1C_PRC","log10_B_HBA1C_PRC", "DU_ACR","log10_DU_ACR","BL_eGFR","KIM1.npx" ,"SYND1.npx","IL.1RT1.npx","WFDC2.npx",      "CD27.npx" , "TNFRSF10A.npx","LAYN.npx","PVRL4.npx", "EDA2R.npx" ,"TNFRSF4.npx" ,"GFR_alpha_1_npx", "TNF.R1.npx", "PI3_npx" , "EFNA4.npx","TNF.R2.npx" ,"DLL1.npx" ,"TNFRSF6B.npx" , "CD160.npx","EPHA2.npx","RELT.npx","LTBR.npx")         

scrambled2 %>%
  tbl_summary(by = Status, missing_text = "(Missing N)",   label = list(FU_TIME ~ "Follow-up Time (year)", FU_TIME_Death ~ "Follow-up Time until Death (year)", SBP_TL ~ "Baseline Systolic blood pressure (mm-Hg)", DBP_TL ~ "Baseline Diatolic blood pressure (mm-Hg)",AGEONSET_TL ~ "Age at T1D onset (year)", BMI_TL ~ "Baseline BMI (kg/m2)", AGE_TL ~ "Baseline Age (year)",B_HBA1C_PRC ~ "Baseline HbA1c (%)",DU_ACR ~ "Baseline ACR (mg/g Cr)",BL_eGFR ~"Baseline eGFR (mL/min/1/.73m2)",log10_B_HBA1C_PRC ~"log10 HbA1c", log10_DU_ACR ~"log10 ACR" ), type = all_continuous() ~ "continuous2", statistic = list(all_continuous() ~ c("{mean}, {sd}","{median} ({p25}, {p75})", "{min}, {max}"),all_categorical() ~ "{n} ({p}%)"))  %>%
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>%
  add_overall() %>%
  add_n() %>%
  modify_header(label ~ "**Variable**") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**Status**") %>%
  modify_footnote( all_stat_cols() ~ "Mean (SD), Median (IQR) or Frequency (%)")%>%
  modify_caption("**Table 1. Patient Characteristics**") %>%
  bold_labels()
```


# Histograms

```{r, histogram, echo=FALSE, message=FALSE, warning=FALSE}
var_num <- scrambled  %>% select("FU_TIME" ,"FU_TIME_Death","SBP_TL","DBP_TL" , "AGEONSET_TL" , "BMI_TL","AGE_TL" , "B_HBA1C_PRC","log10_B_HBA1C_PRC", "DU_ACR","log10_DU_ACR","BL_eGFR","KIM1.npx" ,"SYND1.npx","IL.1RT1.npx","WFDC2.npx",      "CD27.npx" , "TNFRSF10A.npx","LAYN.npx","PVRL4.npx", "EDA2R.npx" ,"TNFRSF4.npx" ,"GFR_alpha_1_npx", "TNF.R1.npx", "PI3_npx" , "EFNA4.npx","TNF.R2.npx" ,"DLL1.npx" ,"TNFRSF6B.npx" , "CD160.npx","EPHA2.npx","RELT.npx","LTBR.npx") 

var_num %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
  facet_wrap(~ key, scales = "free") +
  geom_histogram(bins=20)

```


# Results

## Spearman's Correlation Coefficients



```{r proteins-vec, include=FALSE}
proteins <- c("KIM1.npx",      "SYND1.npx", "IL.1RT1.npx","WFDC2.npx", "CD27.npx",
              "TNFRSF10A.npx", "LAYN.npx",  "PVRL4.npx",  "EDA2R.npx" ,"TNFRSF4.npx" ,
              "GFR_alpha_1_npx", "TNF.R1.npx", "PI3_npx" , "EFNA4.npx","TNF.R2.npx" ,
              "DLL1.npx" ,"TNFRSF6B.npx" , "CD160.npx","EPHA2.npx","RELT.npx",
              "LTBR.npx") 
```

Spearman-correlation coefficient are estimated for the following proteins:

```{r proteins-list, echo=FALSE}
proteins
```

```{r Correlation-table-proteins, echo=FALSE, message=FALSE, warning=FALSE}
protein <- scrambled  %>% select(proteins)
tab_corr(protein, p.numeric=TRUE, corr.method = c( "spearman"))
```

```{r Correlation-proteins, echo=FALSE, message=FALSE, warning=FALSE,fig.width = 45, fig.height=30}

cors <- cor(protein, method = c( "spearman"), use ="complete.obs")
hcl <- hclust(as.dist(1-abs(cors)))
plot(hcl)
ord <- hcl$order
cors_ord <- cors[ord,ord]

cors_ord <- round(cors_ord,2)
corrplot(cors_ord, type ="lower", tl.pos ="lt")
corrplot(cors_ord, method ="number",type ="upper", tl.pos ="n", add=TRUE,  number.cex=3)
```

https://cran.r-project.org/web/packages/corrr/vignettes/using-corrr.html

```{r scrambled-RDS, echo=FALSE, message=FALSE, warning=FALSE}
pathRDS <- "./Data/scrambled.rds"
scrambled <- scrambled %>% mutate(status=CASE_CONTROL, time=FU_TIME)
saveRDS(scrambled, file = pathRDS)
```

Data stored in `scrambled` object are saved in `r pathRDS` file.

